import { NextResponse } from 'next/server';
import { kv } from '@vercel/kv';

// ABSOLUTE CACHE ANNIHILATION
export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const fetchCache = 'force-no-store';

export async function GET() {
  try {
    // Pointing to the fresh _v6 keys generated by the new engine
    const dailySetups = await kv.get('daily_setups_v6') || [];
    const stocksInPlay = await kv.get('stocks_in_play_v6') || [];
    const topMovers = await kv.get('top_movers_v6') || {
      'Mega Caps': [], 'Gainers': [], 'Losers': [], 'ETF Gainers': [], 'ETF Losers': []
    };
    const macroInsights = await kv.get('macro_insights_v6') || null;
    const benchmark = await kv.get('benchmark_v6') || null;
    const lastScanTime = await kv.get('last_scan_time_v6') || Date.now();

    // FORCE BROWSER TO NEVER CACHE THIS RESPONSE
    return NextResponse.json({ 
      success: true,
      lastScanTime: lastScanTime,
      dailySetups: dailySetups, 
      stocksInPlay: stocksInPlay,   
      sips: stocksInPlay,           
      topMovers: topMovers,
      macroInsights: macroInsights,
      benchmark: benchmark  
    }, {
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
        'Surrogate-Control': 'no-store'
      }
    });
    
  } catch (error: any) {
    console.error("CRITICAL_LATEST_ROUTE_ERROR:", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}