import { NextResponse } from 'next/server';
import { kv } from '@vercel/kv';
import { SCANNER_SIP_META, SCANNER_DAILY_META, TOPMOVERS_META } from '@/lib/scanConfig';

// ABSOLUTE CACHE ANNIHILATION
export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const fetchCache = 'force-no-store';

export async function GET() {
  try {
    // Pointing to the fresh _v6 keys generated by the new engine.
    // Parallel reads — these were sequential awaits, which meant six round
    // trips to KV on every poll from every open tab.
    const [
      dailySetups,
      stocksInPlay,
      topMovers,
      macroInsights,
      benchmark,
      lastScanTime,
      storedMeta,
      liveChgMap,
    ] = await Promise.all([
      kv.get('daily_setups_v6'),
      kv.get('stocks_in_play_v6'),
      kv.get('top_movers_v6'),
      kv.get('macro_insights_v6'),
      kv.get('benchmark_v6'),
      kv.get('last_scan_time_v6'),
      kv.get<any>('scan_meta_v6'),
      kv.get<Record<string, [number, number]>>('live_chg_map_v1'),
    ]);

    // Scan-gate metadata for the on-screen "?" key. Prefer whatever the last
    // run persisted — that is the config the scan ACTUALLY enforced. Fall back
    // to the static import so a cold KV (or a deploy before the first run)
    // still renders a key rather than an empty panel.
    const scanMeta = storedMeta && storedMeta.sip
      ? storedMeta
      : { sip: SCANNER_SIP_META, daily: SCANNER_DAILY_META, topMovers: TOPMOVERS_META };

    // FORCE BROWSER TO NEVER CACHE THIS RESPONSE
    return NextResponse.json({ 
      success: true,
      lastScanTime: lastScanTime || Date.now(),
      dailySetups: dailySetups || [], 
      stocksInPlay: stocksInPlay || [],   
      sips: stocksInPlay || [],           
      topMovers: topMovers || {
        'Mega Caps': [], 'Gainers': [], 'Losers': [], 'ETF Gainers': [], 'ETF Losers': []
      },
      macroInsights: macroInsights || null,
      benchmark: benchmark || null,
      liveChgMap: liveChgMap || null,
      scanMeta,
    }, {
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
        'Surrogate-Control': 'no-store'
      }
    });
    
  } catch (error: any) {
    console.error("CRITICAL_LATEST_ROUTE_ERROR:", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}